import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.3";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

// Decrypt token using the same method as github-oauth
async function getEncryptionKey(): Promise<CryptoKey> {
  const ENCRYPTION_SECRET = Deno.env.get("ENCRYPTION_SECRET") || Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")?.slice(0, 32);
  if (!ENCRYPTION_SECRET || ENCRYPTION_SECRET.length < 32) {
    throw new Error("Invalid encryption key");
  }
  
  const encoder = new TextEncoder();
  const keyData = encoder.encode(ENCRYPTION_SECRET.slice(0, 32));
  
  return await crypto.subtle.importKey(
    "raw",
    keyData,
    { name: "AES-GCM" },
    false,
    ["decrypt"]
  );
}

async function decryptToken(encryptedToken: string): Promise<string> {
  try {
    const key = await getEncryptionKey();
    
    // Decode base64
    const combined = Uint8Array.from(atob(encryptedToken), c => c.charCodeAt(0));
    
    // Extract IV and encrypted data
    const iv = combined.slice(0, 12);
    const data = combined.slice(12);
    
    const decrypted = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv },
      key,
      data
    );
    
    const decoder = new TextDecoder();
    return decoder.decode(decrypted);
  } catch {
    // If decryption fails, assume it's a plain text token (backwards compatibility)
    return encryptedToken;
  }
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const SUPABASE_URL = Deno.env.get("SUPABASE_URL");
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

    if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
      throw new Error("Supabase not configured");
    }

    const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
    const body = await req.json();
    const { action, user_id, integration_id, repo_name, repo_description, activity_id, files } = body;

    // Get user's GitHub access token
    const { data: integration, error: intError } = await supabase
      .from("git_integrations")
      .select("id, access_token_encrypted, account_username")
      .eq("user_id", user_id)
      .eq("provider", "github")
      .maybeSingle();

    if (intError || !integration) {
      return new Response(
        JSON.stringify({ error: "GitHub not connected. Please connect your GitHub account first." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Decrypt the token
    const accessToken = await decryptToken(integration.access_token_encrypted);
    const username = integration.account_username;

    // List repositories
    if (action === "list") {
      const response = await fetch("https://api.github.com/user/repos?sort=updated&per_page=50", {
        headers: {
          "Authorization": `Bearer ${accessToken}`,
          "Accept": "application/vnd.github+json",
          "User-Agent": "ActivityForge",
        },
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error("GitHub API error:", response.status, errorText);
        return new Response(
          JSON.stringify({ error: "Failed to fetch repositories. Your token may have expired." }),
          { status: response.status, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const repos = await response.json();
      
      return new Response(
        JSON.stringify({ repos: repos.map((r: any) => ({
          id: r.id,
          name: r.name,
          full_name: r.full_name,
          url: r.html_url,
          description: r.description,
          private: r.private,
          default_branch: r.default_branch,
        })) }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Create new repository
    if (action === "create") {
      const response = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${accessToken}`,
          "Accept": "application/vnd.github+json",
          "User-Agent": "ActivityForge",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: repo_name,
          description: repo_description || "SFMC Custom Activity generated by ActivityForge",
          private: false,
          auto_init: true,
        }),
      });

      if (!response.ok) {
        const error = await response.json();
        return new Response(
          JSON.stringify({ error: error.message || "Failed to create repository" }),
          { status: response.status, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      const repo = await response.json();

      // Store repo link in database
      if (activity_id) {
        await supabase
          .from("git_repositories")
          .insert({
            custom_activity_id: activity_id,
            git_integration_id: integration_id || integration.id,
            provider: "github",
            repository_id: repo.id.toString(),
            repository_name: repo.name,
            repository_url: repo.html_url,
            branch: repo.default_branch,
          });
      }

      return new Response(
        JSON.stringify({
          success: true,
          repo: {
            id: repo.id,
            name: repo.name,
            full_name: repo.full_name,
            url: repo.html_url,
            default_branch: repo.default_branch,
          },
        }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Push files to repository
    if (action === "push") {
      if (!files || !repo_name) {
        return new Response(
          JSON.stringify({ error: "files and repo_name are required" }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Get the default branch SHA
      const refResponse = await fetch(
        `https://api.github.com/repos/${username}/${repo_name}/git/refs/heads/main`,
        {
          headers: {
            "Authorization": `Bearer ${accessToken}`,
            "Accept": "application/vnd.github+json",
            "User-Agent": "ActivityForge",
          },
        }
      );

      let baseSha: string;
      let baseTreeSha: string;

      if (refResponse.ok) {
        const refData = await refResponse.json();
        baseSha = refData.object.sha;

        // Get the tree SHA
        const commitResponse = await fetch(
          `https://api.github.com/repos/${username}/${repo_name}/git/commits/${baseSha}`,
          {
            headers: {
              "Authorization": `Bearer ${accessToken}`,
              "Accept": "application/vnd.github+json",
              "User-Agent": "ActivityForge",
            },
          }
        );
        const commitData = await commitResponse.json();
        baseTreeSha = commitData.tree.sha;
      } else {
        // Empty repo, need to create initial commit
        return new Response(
          JSON.stringify({ error: "Repository is empty. Please initialize with a README first." }),
          { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
        );
      }

      // Create blobs for each file
      const treeItems = [];
      for (const [path, content] of Object.entries(files)) {
        const blobResponse = await fetch(
          `https://api.github.com/repos/${username}/${repo_name}/git/blobs`,
          {
            method: "POST",
            headers: {
              "Authorization": `Bearer ${accessToken}`,
              "Accept": "application/vnd.github+json",
              "User-Agent": "ActivityForge",
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              content: content as string,
              encoding: "utf-8",
            }),
          }
        );
        const blobData = await blobResponse.json();
        treeItems.push({
          path,
          mode: "100644",
          type: "blob",
          sha: blobData.sha,
        });
      }

      // Create new tree
      const treeResponse = await fetch(
        `https://api.github.com/repos/${username}/${repo_name}/git/trees`,
        {
          method: "POST",
          headers: {
            "Authorization": `Bearer ${accessToken}`,
            "Accept": "application/vnd.github+json",
            "User-Agent": "ActivityForge",
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            base_tree: baseTreeSha,
            tree: treeItems,
          }),
        }
      );
      const treeData = await treeResponse.json();

      // Create commit
      const commitResponse = await fetch(
        `https://api.github.com/repos/${username}/${repo_name}/git/commits`,
        {
          method: "POST",
          headers: {
            "Authorization": `Bearer ${accessToken}`,
            "Accept": "application/vnd.github+json",
            "User-Agent": "ActivityForge",
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            message: "Generated by ActivityForge",
            tree: treeData.sha,
            parents: [baseSha],
          }),
        }
      );
      const newCommit = await commitResponse.json();

      // Update ref
      await fetch(
        `https://api.github.com/repos/${username}/${repo_name}/git/refs/heads/main`,
        {
          method: "PATCH",
          headers: {
            "Authorization": `Bearer ${accessToken}`,
            "Accept": "application/vnd.github+json",
            "User-Agent": "ActivityForge",
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            sha: newCommit.sha,
          }),
        }
      );

      // Update last commit in database
      if (activity_id) {
        await supabase
          .from("git_repositories")
          .update({
            last_commit_sha: newCommit.sha,
            last_commit_at: new Date().toISOString(),
          })
          .eq("custom_activity_id", activity_id)
          .eq("provider", "github");
      }

      return new Response(
        JSON.stringify({
          success: true,
          commit_sha: newCommit.sha,
          commit_url: `https://github.com/${username}/${repo_name}/commit/${newCommit.sha}`,
        }),
        { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    return new Response(
      JSON.stringify({ error: "Invalid action" }),
      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("GitHub repos error:", error);
    return new Response(
      JSON.stringify({ error: error instanceof Error ? error.message : "Unknown error" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
